title: I'm Sudheer Aedama, welcome!
description: > # this means to ignore newlines until "baseurl:"
  Scala developer and Functional Programmer.
permalink: ':title/'
#baseurl: "/flexible-jekyll" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Sudheer Aedama # add your name
author-img: me.png # add your photo
about-author: Hi, I am a Scala developer focusing on full-stack development, based in California. # add description
social-twitter: spiritedcentaur # add your Twitter handle
social-github: vaedama # add your Github handle
social-linkedin: sudheer-aedama # add your Linkedin handle
social-email: sudheeraedama@gmail.com # add your Email address

# Disqus
# discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: G-XK8PG97VJM # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji
  - jekyll-target-blank

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
